FROM node:12 AS builder

COPY .env .

COPY package*.json .

# Better to use npm ci to intall all deps from fresh instead of using cached
RUN npm install
# RUN npm ci

##############################################
# App stage #
FROM node:13-alpine

# The WORKDIR command is used to define the working directory of a Docker container at any given time.
WORKDIR /usr/src/app

COPY --from=builder .env .env

ENV REACT_APP_BASE_URL=$REACT_APP_BASE_URL
ENV REACT_APP_REMOTE_API_URL=$REACT_APP_REMOTE_API_URL
ENV REACT_APP_SERVER_URL=$REACT_APP_SERVER_URL
ENV REACT_APP_AUTH0_DOMAIN=$REACT_APP_AUTH0_DOMAIN
ENV REACT_APP_AUTH0_CLIENT_ID=$REACT_APP_AUTH0_CLIENT_ID
ENV REACT_APP_AUTH0_AUDIENCE=$REACT_APP_AUTH0_AUDIENCE
ENV REACT_APP_AUTH0_SECRET=$REACT_APP_AUTH0_SECRET
ENV SERVER_PORT=8000
ENV CLIENT_ORIGIN_URL=$CLIENT_ORIGIN_URL
ENV AUTH0_AUDIENCE=$AUTH0_AUDIENCE
ENV AUTH0_DOMAIN=$AUTH0_DOMAIN
# ENV REACT_APP_BASE_URL=http://localhost:3000
# ENV REACT_APP_REMOTE_API_URL=http://localhost:8000
# ENV REACT_APP_SERVER_URL=http://localhost:8000
# ENV REACT_APP_AUTH0_DOMAIN=dev-405n1e6w.auth0.com
# ENV REACT_APP_AUTH0_CLIENT_ID='ouQeFaroORjm08Dp6slPLQaNYri0sNY5'
# ENV REACT_APP_AUTH0_AUDIENCE=https://api.quantumcoasters.com
# ENV REACT_APP_AUTH0_SECRET='moWYcL19X4PtwLFqtRx2QiB5l7KfzUqIM1LZ31rzXjuWNeJx_w1OJqoueYKP_4kx'
# ENV SERVER_PORT=8000
# ENV CLIENT_ORIGIN_URL=http://localhost:3000
# ENV AUTH0_AUDIENCE=https://api.quantumcoasters.com
# ENV AUTH0_DOMAIN=https://dev-405n1e6w.auth0.com

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]
