FROM node:12

# The WORKDIR command is used to define the working directory of a Docker container at any given time.
WORKDIR /quantumcoasters

COPY package.json /quantumcoasters/

# Better to use npm ci to intall all deps from fresh instead of using cached
# RUN npm install
RUN npm ci


COPY . /quantumcoasters/
