FROM node:10

# The WORKDIR command is used to define the working directory of a Docker container at any given time.
WORKDIR /quantum-application

COPY package.json /quantum-application/

RUN npm install

COPY . /quantum-application/
